export const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    experience: 15,
    rating: 4.8,
    fees: 150,
    availability: ["Mon", "Wed", "Fri"],
    email: "sarah.johnson@hospital.com",
    phone: "+1 234-567-8901",
    about:
      "Specialized in preventive cardiology and heart disease management with over 15 years of experience.",
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "Dermatologist",
    experience: 10,
    rating: 4.9,
    fees: 120,
    availability: ["Tue", "Thu", "Sat"],
    email: "michael.chen@hospital.com",
    phone: "+1 234-567-8902",
    about: "Expert in cosmetic dermatology and skin cancer treatment.",
  },
  {
    id: 3,
    name: "Dr. Emily Rodriguez",
    specialty: "Pediatrician",
    experience: 12,
    rating: 4.7,
    fees: 100,
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    email: "emily.rodriguez@hospital.com",
    phone: "+1 234-567-8903",
    about:
      "Dedicated to providing comprehensive care for children from infancy through adolescence.",
  },
  {
    id: 4,
    name: "Dr. James Wilson",
    specialty: "Orthopedic",
    experience: 20,
    rating: 4.6,
    fees: 180,
    availability: ["Mon", "Wed", "Fri"],
    email: "james.wilson@hospital.com",
    phone: "+1 234-567-8904",
    about: "Specializes in sports injuries and joint replacement surgery.",
  },
  {
    id: 5,
    name: "Dr. Lisa Anderson",
    specialty: "Neurologist",
    experience: 18,
    rating: 4.9,
    fees: 200,
    availability: ["Tue", "Thu"],
    email: "lisa.anderson@hospital.com",
    phone: "+1 234-567-8905",
    about:
      "Expert in treating neurological disorders including epilepsy and migraines.",
  },
  {
    id: 6,
    name: "Dr. David Martinez",
    specialty: "General Physician",
    experience: 8,
    rating: 4.5,
    fees: 80,
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    email: "david.martinez@hospital.com",
    phone: "+1 234-567-8906",
    about: "Providing comprehensive primary care for patients of all ages.",
  },
  {
    id: 7,
    name: "Dr. Rachel Thompson",
    specialty: "Gynecologist",
    experience: 14,
    rating: 4.8,
    fees: 140,
    availability: ["Mon", "Wed", "Fri"],
    email: "rachel.thompson@hospital.com",
    phone: "+1 234-567-8907",
    about: "Specialized in women's health and prenatal care.",
  },
  {
    id: 8,
    name: "Dr. Robert Kim",
    specialty: "Psychiatrist",
    experience: 16,
    rating: 4.7,
    fees: 160,
    availability: ["Tue", "Wed", "Thu"],
    email: "robert.kim@hospital.com",
    phone: "+1 234-567-8908",
    about:
      "Expert in treating anxiety, depression, and other mental health conditions.",
  },
];

export const specialties = [
  "All Specialties",
  "Cardiologist",
  "Dermatologist",
  "Pediatrician",
  "Orthopedic",
  "Neurologist",
  "General Physician",
  "Gynecologist",
  "Psychiatrist",
];

export const timeSlots = [
  "09:00 AM",
  "10:00 AM",
  "11:00 AM",
  "12:00 PM",
  "02:00 PM",
  "03:00 PM",
  "04:00 PM",
  "05:00 PM",
];
